apiVersion: apps/v1
kind: Deployment
metadata:
  name: asthropic-backend
  namespace: asthropic-prod
  labels:
    app: asthropic-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asthropic-backend
  template:
    metadata:
      labels:
        app: asthropic-backend
    spec:
      containers:
      - name: backend
        image: sajal30/asthropic-chatapp-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: asthropic-config
        - secretRef:
            name: asthropic-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
