apiVersion: v1
kind: Service
metadata:
  name: asthropic-backend-service
  namespace: asthropic-prod
spec:
  selector:
    app: asthropic-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
